title: Debbie No
logo: https://github.com/dnovalina/Debbie-No/blob/ba155553643350f7579c5e9da2e530dbd175ce7b/img/photo.jpg
show_downloads: true
#description: text below image
theme: jekyll-theme-minimal
