title: Debbie No

author: debbieno

#logo: https://github.com/dnovalina/Debbie-No/blob/ba155553643350f7579c5e9da2e530dbd175ce7b/img/photo.jpg

avatar: "/assets/img/photo.jpg"

round-avatar: true
#show_downloads: true

theme: jekyll-theme-minimal
